theme: jekyll-theme-minimal
title: Robert Olander
description: Welcome to my project page! I'm sharing some of the more interesting things I'm building or problems I'm investigating.
logo: rsolander.github.io/forest_pic.jpeg
